chromatic-protocol/frontend

package.json, src/hooks/useChromaticClient.ts, src/hooks/useFeeRate.ts, yarn.lock
fix: client's signer could be undefined
update sdk deps
Fixes #226
=> fix chromatic client hook

.gitignore, package.json
=> chore: bump version to use npmjs registry

src/hooks/useChromaticClient.ts, src/hooks/usePoolReceipt.ts, src/hooks/usePosition.ts
- 클라이언트 Signer Provider 업데이트
- 유동성 Claim
- Positions 불러오기
=> chore: `sdk` version update

src/hooks/useLiquidityPool.ts, src/hooks/useMarket.ts, src/hooks/useOwnedLiquidityPools.ts, src/hooks/usePoolInput.ts, src/hooks/usePoolReceipt.ts, src/hooks/usePosition.ts, src/hooks/useSettlementToken.ts, src/hooks/useTokenTransaction.ts, src/hooks/useTradeInput.ts, src/pages/pool/index.tsx, src/pages/trade/index.tsx, src/stories/atom/Toast/index.tsx, src/stories/atom/TooltipGuide/index.tsx, src/stories/molecule/PoolProgress/index.tsx, src/stories/molecule/TradeContent/index.tsx, src/stories/template/PoolPanel/index.tsx, src/stories/template/RemoveLiquidityModal/index.tsx
- Show toast messages
- Select markets
- Select settlement tokens
- Add liquidity, and claim CLB
- Remove liquidity, and withdraw settlement tokens
- Open positions
- Close positions
- Claim positions
- Token transaction with Chromatic account
- Deposit
- Withdraw
- Decimals issue
- Expected trade fee
- Liquidity information
=> feat: show toast components with messages

src/stories/atom/Input/stories.ts, src/stories/atom/OptionInput/stories.ts, src/stories/molecule/AssetPopover/index.tsx, src/stories/molecule/WalletPopover/index.tsx, src/stories/template/Footer/index.tsx, src/stories/template/Header/index.tsx
=> fix: static image url

src/configs/token.ts
=> fix: price feed address

src/stories/atom/FillUpChart/stories.ts, src/stories/atom/RangeChart/stories.ts, src/stories/template/PoolPanel/stories.ts, src/stories/template/TradePanel/stories.ts
Fixes #200 
@dia-nn 차트용 샘플데이터 추가했습니다
=> Jaycho 46/issue200

src/hooks/useActiveElement.ts, src/hooks/usePoolInput.ts, src/hooks/usePoolRemoveInput.ts, src/hooks/useTokenTransaction.ts, src/hooks/useTradeInput.ts, src/stories/atom/Input/index.tsx, src/stories/molecule/TradeContent/index.tsx, src/stories/template/RemoveLiquidityModal/index.tsx
- Show number values with commas
- `3000` is shown as `3,000`
- Check what element is active
- Element which is not active should show number value with decimals by default.
=> fix: show numbers with commas

src/App.tsx
=> fix: set dedicated `CHAIN` configuration of wagmi

src/index.css, src/pages/pool/index.tsx, src/pages/trade/index.tsx, src/stories/atom/LeverageOption/index.tsx, src/stories/atom/Select/style.css, src/stories/atom/Slider/components/index.tsx, src/stories/atom/Slider/index.tsx, src/stories/molecule/TradeContent/index.tsx, src/stories/template/Header/index.tsx, src/stories/template/MainBar/index.tsx, src/stories/template/TradePanel/index.tsx, tailwind.config.js
- fix z-index (Slider)
- fix panel, page width
- style dropdown detail
=> Dia/fix UI error

src/stories/template/TradeBar/index.tsx, src/typings/position.ts
- Filter positions by the selected market
- Show all positions if no market selected
=> feat: filter positions

src/App.tsx
=> fix: change multicall address

src/App.tsx, src/constants/contracts.ts, src/hooks/useChromaticClient.ts, src/hooks/useConnectOnce.ts, src/pages/pool/index.tsx, src/pages/trade/index.tsx
- Use chain configs
- On connect manually
- Three chains used
- Hardhat
- Arbitrum
- Arbitrum Goerli
=> fix: chain configs for connectors

src/App.tsx, src/hooks/useLiquidityPool.ts, src/hooks/usePriceFeed.ts, src/hooks/useTokenBalance.ts, src/stories/template/Header/index.tsx, src/stories/template/Header/stories.ts
=> refactor: remove multical usage

src/stories/molecule/TradeContent/index.tsx
=> Jaycho 46/issue238

package.json, src/hooks/useAddLiquidity.ts, src/hooks/useOpenPosition.ts, src/hooks/useOwnedLiquidityPools.ts, src/hooks/usePoolReceipt.ts, src/hooks/usePosition.ts, src/hooks/useRemoveLiquidities.ts, src/hooks/useRemoveLiquidity.ts, src/hooks/useSettlementToken.ts, src/stories/molecule/AssetPopover/index.tsx, src/stories/molecule/PoolProgress/index.tsx, src/stories/template/TradeBar/index.tsx, yarn.lock
- Toast error messages
- Use message `property` instead of `reason`
- Guide
- Show guide component when events are fired
- Open positions
- Add liquidities
- Show account balance with token name
=> fix: show toast when error exists

src/stories/molecule/AssetPopover/index.tsx
=> Jaycho 46/issue290

src/stories/molecule/AssetPopover/index.tsx
- AssetPanel
- Show token balances with token address
- Handle option buttons click
- Confirm deposit and withdraw are working
=> fix: show token balance

package.json, yarn.lock
=> chore: upgrade chromatic sdk

package.json, src/store/reducer/pools/index.ts, src/stories/template/PoolPanel/index.tsx, yarn.lock
- Redux store
- Find what tab is selected between `Long counter lp` and `Short counter lp`
- Select all bin items to remove
- All bin items on each counter lp will be selected with check sign
- By which tab are selected
- All bin items will be unselected on clicking same button again
- If all bin items are selected already.
=> feat: Select All liquidities to remove on each counter

package.json, src/stories/atom/RangeChart/index.tsx, yarn.lock
=> Jaycho 46/issue308

src/hooks/useTokenBalance.ts, src/stories/molecule/WalletPopover/index.tsx, src/utils/index.ts
=> refactor: change fetch key

src/pages/trade/index.tsx, src/stories/template/TradePanel/index.tsx
=> Jaycho 46/issue316

src/configs/decimals.ts, src/hooks/usePoolInput.ts, src/hooks/usePosition.ts, src/hooks/useRemoveLiquidity.ts, src/hooks/useTokenTransaction.ts, src/stories/atom/Input/index.tsx, src/stories/molecule/TradeContent/index.tsx, src/stories/template/PoolPanel/index.tsx, src/stories/template/TradeBar/index.tsx, src/typings/position.ts
- Position
- Format position attributes with token decimals
- Ratio with profit and loss prices
- Position PnL
- Pool
- Average clb token value
=> fix: format `bigint`s

.gitignore, package.json, src/main.tsx, vite.config.ts, yarn.lock
=> chore: apply `sentry`

src/hooks/useClaimPosition.ts, src/hooks/usePosition.ts
- Claim positions on click `claim` button
- Check positions if position can be claimed
=> fix: claim positions

package.json, src/configs/decimals.ts, src/hooks/usePosition.ts, src/stories/template/TradeBar/index.tsx, yarn.lock
- Show profit and loss percentage of each position
- Decimal configs
=> fix: Show profit and loss percentage

package.json, yarn.lock
=> chore: sdk version

src/hooks/useMarket.ts, src/pages/pool/index.tsx
=> The token address copy button is copying an incorrect CLB token address.

src/hooks/useTradeInput.ts
- Get trade fee by trade input
=> fix: get trade fee

src/hooks/useOpenPosition.ts
=> SyntaxError: Cannot convert 188.05499999999998 to a BigInt

src/stories/atom/PopoverArrow/index.tsx, src/stories/atom/PopoverArrow/stories.ts, src/stories/template/TradeBar/index.tsx
- fix `button` in `button` #248 
- replace `button` to `span`
- update component name: `PopoverButton` to `PopoverArrow`
=> Dia/fix issue#248

src/hooks/useChromaticClient.ts, src/hooks/useMargins.ts, src/hooks/useUsumAccount.ts, src/pages/trade/index.tsx, src/stories/molecule/AssetPopover/index.tsx, src/stories/template/MainBar/index.tsx
- syncronize current selected account of metamask
- fix not updated balance sometimes
- distinguish between NA balance and `0.00`
=> fix: sync walletClient account to current

package.json, src/stories/template/PoolPanel/index.tsx, yarn.lock
=> fix: values of remove liquidity

src/pages/pool/index.tsx, src/stories/molecule/PoolProgress/index.tsx
=> add PoolProgress oracle timestamp timer

src/App.tsx, src/configs/wagmiClient.ts, src/hooks/useChartData.ts, src/hooks/useChromaticClient.ts, src/hooks/useFeeRate.ts, src/hooks/useLiquidityPool.ts, src/hooks/useMarket.ts, src/hooks/useMarketFactory.ts, src/hooks/useOracleVersion.ts, src/hooks/useOwnedLiquidityPool.ts, src/hooks/useOwnedLiquidityPools.ts, src/hooks/usePoolReceipt.ts, src/hooks/usePosition.ts, src/hooks/usePriceFeed.ts, src/hooks/useUsumAccount.ts, src/main.tsx, src/pages/trade/index.tsx, src/stories/template/PoolPanel/index.tsx, src/utils/index.ts, src/utils/number.ts
refactoring SWR fetch key
fix account loading
Fixes #342
=> Kayden-fi/issue342

src/main.tsx
=> chore: set `denyUrls` of sentry

src/hooks/useMarketLocal.ts, src/hooks/useOwnedLiquidityPool.ts, src/hooks/useOwnedLiquidityPools.ts, src/hooks/usePoolInput.ts, src/hooks/usePoolRemoveInput.ts, src/hooks/useRemoveLiquidities.ts, src/hooks/useTokenLocal.ts, src/hooks/useUsumAccount.ts, src/pages/pool/index.tsx, src/stories/molecule/LiquidityItem/index.tsx, src/stories/template/PoolPanel/index.tsx, src/stories/template/RemoveLiquidityModal/index.tsx, src/stories/template/RemoveMultiLiquidityModal/index.tsx, src/stories/template/RemoveMultiLiquidityModal/stories.ts
- Input to remove liquidity bins
- Use token decimals
- Can remove with removable amount
- Input CLB balance to remove bins
- On change Metamask account
- Can create new account if there are no chromatic accounts.
- Can deposit tokens if user has the account.
- Can update token balances
- Remove Liquidity Modal
- Show token name instead
- Quantity with decimals
- Can remember the last selected token, and market.
- #338
=> fix: UI / UX errors

src/stories/molecule/PoolProgress/index.tsx
=> fix PoolProgress token name

src/hooks/useOracleProperties.ts, src/stories/molecule/TradeContent/index.tsx
=> fix: handle leverage level property

src/hooks/useTokenTransaction.ts, src/stories/molecule/AssetPopover/index.tsx, src/stories/template/MainBar/index.tsx
- Close `AssetPanel` after deposit or withdraw tokens
- Fetch Chromatic balances after waiting token transactions
- Show toasts after token transactions
=> fix: Token transaction

src/hooks/usePoolReceipt.ts, src/stories/molecule/PoolProgress/stories.ts
- Fetch receipts
- Duplicated receipt id
=> fix: fetch receipts

src/stories/template/RemoveLiquidityModal/index.tsx
=> fix: `Removable Liquidity` percentage format

package.json, src/stories/atom/ScrollAni/index.tsx, src/stories/template/RemoveMultiLiquidityModal/index.tsx, yarn.lock
- Show arrow animation before user scroll
- Check if scroll action is needed to see bins
- Compare `scrollHeight` and `clientHeight` attributes
- Handle resize event
- Fixes #159
=> feat: show arrow animation before scroll

src/utils/number.ts
=> fix: division by zero

package.json, yarn.lock
=> chore: update chromatic sdk

src/pages/pool/index.tsx, src/stories/container/PoolPanel/index.tsx, src/stories/molecule/AccountPopover/index.tsx, src/stories/molecule/WalletPopover/index.tsx, src/stories/template/PoolPanel/index.tsx
=> add link to block scanner

src/pages/pool/index.tsx, src/pages/trade/index.tsx, src/stories/atom/Button/style.css, src/stories/atom/Guide/index.tsx, src/stories/atom/Input/style.css, src/stories/atom/OptionInput/index.tsx, src/stories/atom/Progress/index.tsx, src/stories/atom/Progress/style.css, src/stories/atom/Select/style.css, src/stories/atom/Slider/components/index.tsx, src/stories/atom/Tag/style.css, src/stories/atom/Toggle/style.css, src/stories/molecule/AccountPopover/index.tsx, src/stories/molecule/LiquidityItem/index.tsx, src/stories/molecule/PoolProgress/index.tsx, src/stories/molecule/TradeContent/index.tsx, src/stories/molecule/WalletPopover/index.tsx, src/stories/template/Header/index.tsx, src/stories/template/PoolPanel/index.tsx, src/stories/template/RemoveLiquidityModal/index.tsx, src/stories/template/RemoveMultiLiquidityModal/index.tsx, src/stories/template/TradeBar/index.tsx, tailwind.config.js
- renew color palette
black: '#030303',
grayLbg: '#FCFCFC',
grayL1: '#EEEEEE',
grayL2: '#D4D4D4',
grayDbg: '#151515',
grayD1: '#333333',
grayD2: '#4D4D4D',
=> style: add, renew colors

src/hooks/useChartData.ts, src/typings/chart.ts
=> fix `CLB Price`

package.json, yarn.lock
=> chore: update `@chromatic-protocol/sdk-viem`

src/hooks/usePoolReceipt.ts, src/stories/molecule/PoolProgress/index.tsx
- Filter receipts by action
- Check receipts of each action could be claimed
- Claim filtered receipts by action
- Show CLB amount remaining on burning receipts
- Fixes #417
=> refactor: Filter receipts by action

package.json, src/hooks/useSettlementToken.ts, src/hooks/useTradeInput.ts, src/stories/atom/Input/index.tsx, src/stories/container/TradeContent/index.tsx, src/stories/molecule/AccountPopover/stories.ts, src/stories/molecule/LiquidityItem/stories.ts, src/stories/molecule/MarketSelect/stories.ts, src/stories/molecule/PoolProgress/stories.ts, src/stories/molecule/TradeContent/index.tsx, src/stories/molecule/TradeContent/stories.ts, src/stories/molecule/WalletPopover/stories.ts, src/stories/template/PoolPanel/stories.ts, src/stories/template/RemoveLiquidityModal/stories.ts, src/stories/template/RemoveMultiLiquidityModal/stories.ts, src/stories/template/TradeBar/stories.ts, src/typings/market.ts, src/typings/trade.ts, src/utils/number.ts, yarn.lock
=> Jaycho 46/issue397

src/hooks/usePositions.ts, src/stories/container/TradeBar/index.tsx
- Sort positions by descending order of each ids of positions
- Toast message when oracle version has been updated
- Opening positions at previous oracle version
- Closing positions at previous oracle version
=> fix: Positions UI / UX issues

src/hooks/useOracleVersion.ts
- Show the selected liquidity pool when not connected yet.
fixes #426
=> fix: Show pools when not connected

src/stories/molecule/TradeContent/index.tsx
=> fix: open position

src/stories/molecule/TradeContent/index.tsx, src/stories/template/PoolPanel/index.tsx
=> Misaligned liquidity value above the liquidity bin chart

src/hooks/useTradeInput.ts, src/stories/molecule/TradeContent/index.tsx
=> Jaycho 46/issue428

src/hooks/useChainListener.ts, src/hooks/useSwitchChain.ts, src/pages/pool/index.tsx, src/pages/trade/index.tsx, src/stories/container/ChainModal/index.tsx, src/stories/container/Header/index.tsx, src/stories/template/Header/index.tsx, src/stories/template/Modal/index.tsx
- Show the modal when user selected wrong chains
- Disappear when clicking the button above
- Try to check again when clicking the button `Try Again`
- Switch correct chain by clicking a button on Header
fixes #437
=> fix: Show modal to notify about chains

src/index.css, src/stories/atom/TooltipAlert/index.tsx, src/stories/molecule/WalletPopover/index.tsx, src/stories/template/Header/index.tsx, src/stories/template/Modal/index.tsx, src/stories/template/Modal/style.css, src/stories/template/RemoveLiquidityModal/index.tsx, src/stories/template/RemoveMultiLiquidityModal/index.tsx, src/stories/template/TradeBar/index.tsx
- fix z-index for `tooltip`, `modal`
- network tooltip positon
- style backdrop
=> Dia/fix global UI (tooltip, backdrop)

src/hooks/useAddLiquidity.ts, src/hooks/useClaimPosition.ts, src/hooks/useClosePosition.ts, src/hooks/useMargins.ts, src/hooks/useOpenPosition.ts, src/hooks/usePoolReceipt.ts, src/hooks/useRemoveLiquidityAmounts.ts, src/hooks/useRemoveLiquidityBins.ts, src/hooks/useTokenTransaction.ts, src/stories/container/TradeBar/index.tsx, src/stories/molecule/AccountPopover/index.tsx
- Update toast messages 
- When user removed liquidities
- When user rejected transactions
- When user started to open or close positions
- When user claims positions already closed
fixes #444
=> fix: toast message when removing liquidities

package.json, yarn.lock
=> Using incorrect oracle price for the positions

src/hooks/useChromaticAccount.ts, src/stories/container/WalletPopover/index.tsx
- Create the contract account with my wallet address when I clicked the button `Create Account` on the component `WalletPopover` below.
- Show toast message if new account would be created successfully
- Message
`The account addtress is being generated on the chain. This process may take approximately 10 seconds or more.`
=> fix: create account on click button below

src/hooks/useChromaticAccount.ts, src/hooks/useCreateAccount.ts, src/stories/container/AccountPopover/index.tsx, src/stories/container/WalletPopover/index.tsx
- Show toast message when approve transactions
- Creating account in `WalletPopover`
- After clicking the button `Approval` on Metamask
- Not After creating accounts has been completed
fixes #452
=> fix: show toast message after approval (with fixme)

package.json, yarn.lock
- SDK version update
- Fetch positions after opening a new position on local chain
=> chore: sdk update

src/hooks/useMargins.ts, src/hooks/useMarket.ts, src/hooks/usePositions.ts, src/stories/molecule/PoolProgress/stories.ts, src/stories/molecule/WalletPopover/stories.ts, src/stories/template/TradeBar/stories.ts, src/typings/market.ts, src/typings/position.ts
- Token address property on Market
- Check token addresses are equal to get positions
- Token address parameter
- Token address property on market parameter
- Check the market correspond to the selected token
=> fix: Check token addresses are valid

src/hooks/useChartData.ts, src/stories/atom/RangeChart/stories.ts, src/stories/molecule/LiquidityTooltip/index.tsx, src/stories/molecule/MarketSelect/index.tsx, src/stories/molecule/TradeContent/index.tsx, src/stories/template/PoolPanel/index.tsx, src/stories/template/PoolPanel/stories.ts, src/stories/template/TradeBar/index.tsx, src/typings/chart.ts, src/utils/clipboard.ts
- Show toast messages on clicking copy buttons
- Copy addresses
- Format market prices on the component `MarketSelect`
- Trade page
- Format index prices
- Take profit price
- Stop loss price
- Display hours, minutes, and seconds of each entry times
- Pool page
- Show CLB price on each chart tooltips
=> fix: Reported UI UX issues

src/hooks/useChartData.ts, src/stories/container/PoolPanel/index.tsx, src/stories/container/TradeContent/index.tsx, src/stories/container/TradePanel/index.tsx, src/stories/molecule/LiquidityTooltip/index.tsx, src/stories/molecule/LiquidityTooltip/stories.ts, src/stories/molecule/TradeContent/index.tsx, src/stories/template/PoolPanel/index.tsx, src/stories/template/PoolPanel/stories.ts, src/stories/template/TradePanel/index.tsx, src/stories/template/TradePanel/stories.ts, src/typings/chart.ts
- Show liquidity bar on chart
- Prevent showing black color when liquidity is low
fixes: #473
=> fix: Chart color

src/index.css, src/stories/atom/AddressCopyButton/index.tsx, src/stories/atom/Avatar/style.css, src/stories/atom/FillUpChart/style.css, src/stories/atom/PopoverArrow/index.tsx, src/stories/atom/SkeletonElement/style.css, src/stories/atom/Tabs/style.css, src/stories/atom/Tag/style.css, src/stories/atom/TextRow/index.tsx, src/stories/atom/Thumbnail/index.tsx, src/stories/molecule/AccountPopover/style.css, src/stories/molecule/MarketSelect/style.css, src/stories/molecule/PoolProgress/index.tsx, src/stories/molecule/TradeContent/index.tsx, src/stories/molecule/WalletPopover/index.tsx, src/stories/molecule/WalletPopover/style.css, src/stories/template/Header/index.tsx, src/stories/template/Modal/index.tsx, src/stories/template/RemoveLiquidityModal/index.tsx, src/stories/template/RemoveMultiLiquidityModal/index.tsx, src/stories/template/TradeBar/index.tsx, src/stories/template/TradePanel/index.tsx, tailwind.config.js
- update color (to cool-gray tone, lighten)
- add color for `PoolProgress` tags
---
- todo
- add color on long/short in `TradeBar`
- update chart colors
=> update darkmode colors

src/hooks/usePreviousVersion.ts, src/index.css, src/stories/container/MarketSelect/index.tsx, src/stories/molecule/MarketSelect/index.tsx, src/stories/molecule/PopoverItem/hooks.ts, src/stories/molecule/PopoverItem/index.tsx, src/stories/molecule/PopoverItem/stories.ts, src/utils/oracle.ts, tailwind.config.js
- Hooks to get previous oracle prices with the selected market
- Change text color when current price is different with previous one.
- Use the color `text-price-higher` if current price is higher.
- Use `text-price-lower` if current is lower.
- Separate the component `PopoverItem`
- Compare prices of each markets
=> fix: Colors of each prices in `MarketSelect`

src/configs/widget.ts, src/stories/molecule/TradingViewWidget/__mocks__/hooks.ts, src/stories/molecule/TradingViewWidget/hooks.ts, src/stories/molecule/TradingViewWidget/index.tsx, src/stories/molecule/TradingViewWidget/stories.ts, src/typings/chart.ts
- Show the chart widget components
- Provide how the price of the selected market has been changed
- Component hooks
- Mocked hooks for Storybook
- Configs for displaying charts
- Typings for charts
- Configs for charts
- Market symbols.
fixes #483
=> feat: Show chart widgets by the selected market

package.json, src/hooks/useOpenPosition.ts, src/hooks/useTradeInput.ts, src/stories/atom/Input/index.tsx, src/stories/atom/Slider/index.tsx, src/stories/molecule/AmountSwitch/index.tsx, src/stories/molecule/AssetPanel/hooks.tsx, src/stories/molecule/TradeContent/hooks.tsx, src/stories/molecule/TradeContent/index.tsx, src/stories/molecule/WalletPopover/hooks.tsx, src/typings/trade.ts, src/utils/number.ts, yarn.lock
=> Jaycho 46/issue478

src/hooks/useOwnedLiquidityPools.ts, src/stories/molecule/WalletPopover/hooks.tsx
- Fixed pool summary data
- Sum of user's bins on each markets
- The number of user's bins
fixes #493
=> fix: Invalid pool summary

src/stories/template/TradePanel/hooks.tsx, src/stories/template/TradePanel/index.tsx
The part where the buttons are connected in the opposite direction has been corrected.
If you press the button on the right, the right panel should be closed.
=> fix: issuetradePanel view-wide button #496

src/index.css, src/pages/tradeV2/index.tsx, src/stories/atom/Button/index.tsx, src/stories/atom/Button/style.css, src/stories/atom/Select/index.tsx, src/stories/atom/Select/style.css, src/stories/atom/Tabs/style.css, src/stories/atom/Tag/style.css, src/stories/molecule/MarketSelectV2/index.tsx, src/stories/molecule/MarketSelectV2/style.css, src/stories/molecule/PositionItemV2/__mocks__/hooks.tsx, src/stories/molecule/PositionItemV2/hooks.tsx, src/stories/molecule/PositionItemV2/index.tsx, src/stories/molecule/PositionItemV2/stories.ts, src/stories/molecule/TradeContentV2/index.tsx, src/stories/molecule/TradingViewWidget/index.tsx, src/stories/template/MainBarV2/index.tsx, src/stories/template/MainBarV2/style.css, src/stories/template/TradeChartView/index.tsx, src/stories/template/TradeManagement/__mocks__/hooks.ts, src/stories/template/TradeManagement/hooks.ts, src/stories/template/TradeManagement/index.tsx, src/stories/template/TradeManagement/stories.ts, src/stories/template/TradeManagement/style.css, src/stories/template/TradePanelV2/index.tsx, tailwind.config.js
done
- update layout, resizable for V2
- replace TradeBar to TradeManagement
- update MarketSelect popover inner
- MainBar popover backdrop
- trades layout width (default ratio)
---
todo later
- TradeManagement > history, trades list
- TradeManagement > position list > status
=> Dia/update trade v2 (layout)

src/stories/atom/ResizablePanel/index.tsx, src/stories/molecule/AdvancedChart/utils.ts, src/stories/template/TradeChartPanel/index.tsx
=> Transparent chart

package.json, src/configs/token.ts, src/hooks/useLpReceipts.ts, src/hooks/usePriceFeed.ts, src/hooks/useTradeHistory.ts, src/stories/molecule/AccountPanelV3/index.tsx, src/stories/molecule/AccountPopoverV3/index.tsx, src/stories/molecule/AdvancedChart/__mocks__/hooks.ts, src/stories/molecule/AdvancedChart/hooks.ts, src/stories/molecule/AdvancedChart/index.tsx, src/stories/molecule/PoolProgressV2/hooks.tsx, src/stories/molecule/WalletPopover/hooks.tsx, src/stories/molecule/WalletPopoverV3/hooks.tsx, yarn.lock
- Separated hooks to initialize the Advanced chart
- Hooks to be used in Storybook
- Remove unused props, ternary operators.
=> refactor: Frontend

src/stories/atom/Input/index.tsx, src/stories/template/PoolPanelV2/hooks.tsx, src/stories/template/PoolPanelV2/index.tsx, src/typings/intl.ts, src/utils/number.ts
- Switch tokens by clicking tabs
- Use settlement token on adding token into LP, and CLP token on removing from
- Update token amount by clicking input options
- Remove unused variables
- Format number input
- Use truncate as rounding mode
fixes #547
=> fix: Switch tokens by clicking tabs on pool v3

package.json, src/stories/atom/PoolChart/hooks.tsx, src/stories/atom/PoolChart/index.tsx, src/stories/template/PoolPanelV2/hooks.tsx, src/stories/template/PoolPanelV2/index.tsx, yarn.lock
=> fix: hide handles in rangeChart

package.json, src/hooks/useChromaticAccount.ts, src/hooks/useChromaticLp.ts, src/hooks/useLiquidityPool.ts, src/hooks/useLpReceipts.ts, src/hooks/useOracleBefore24Hours.ts, src/hooks/useOwnedLiquidityPools.ts, src/hooks/usePoolReceipt.ts, src/hooks/usePositions.ts, src/hooks/usePreviousOracle.ts, src/hooks/useTradeInput.ts, src/store/reducer/trades/index.ts, src/stories/molecule/WalletPopoverV3/hooks.tsx, src/stories/molecule/WalletPopoverV3/index.tsx, src/stories/template/PoolStat/hooks.ts, src/typings/lp.ts, src/utils/promise.ts, yarn.lock
- Reduce times to fetch positions
- Manage fetch keys
- Polling interval in Wagmi client
- Fix max allowable fee
- Get fee percentage from input forms and Liquidity bins
fixes #556
=> fix: Position Issues

.github/workflows/chromatic.yml, codegen/lp.ts, src/App.tsx, src/bigint/index.ts, src/hooks/useLpReceipts.ts, src/stories/molecule/AdvancedChart/stories.ts, src/stories/template/PoolPanelV2/index.tsx, src/stories/template/PoolStat/hooks.ts, vite.config.ts
- Hide CLP symbols of each LPs & show `CLP` instead
- Pool detail components
- Story file of the advanced chart component
- Add environment variables to check environment
- Don't use top level await vite plugin in storybook build
fixes #561
=> Fix: Frontend UI Issues

src/hooks/useCLPPerformace.ts, src/hooks/useMargins.ts, src/hooks/usePositionFilterLocal.ts, src/pages/tradeV3/index.tsx, src/stories/molecule/AccountPanelV3/hooks.tsx, src/stories/molecule/AccountPanelV3/index.tsx, src/stories/molecule/AccountPopoverV3/hooks.tsx, src/stories/molecule/LiquidityTooltip/index.tsx, src/stories/molecule/MarketSelectV3/hooks.tsx, src/stories/molecule/SelectedTooltip/index.tsx, src/stories/molecule/TradeContentV3/hooks.tsx, src/stories/template/PoolStat/index.tsx, src/stories/template/TradeManagementV3/hooks.ts, src/stories/template/TradeManagementV3/index.tsx, src/utils/number.ts
- Format bigint value with rounding modes
- Show trade logs & history when data is ready
- Format values in tooltips
- Show available margin & total balances of my Chromatic account
- Switch visible points of each other
- Filter positions by selected options
- More issues from QA
=> fix: Frontend QA

src/hooks/useLpReceiptCount.ts, src/hooks/useLpReceipts.ts, src/stories/molecule/PoolProgressV2/__mocks__/hooks.tsx, src/stories/molecule/PoolProgressV2/hooks.tsx, src/stories/molecule/PoolProgressV2/index.tsx, src/typings/lp.ts
- Storybook build error on `PoolProgress` component
- Returned value of mocking hooks
=> hotfix: Storybook build error

src/hooks/usePythPrice.ts, src/lib/pyth/streaming.ts, src/stories/molecule/MarketSelectV3/hooks.tsx
=> Jaycho 46/issue581

package.json, src/stories/atom/PoolChart/hooks.tsx, src/stories/atom/TradeChart/hooks.tsx, src/stories/molecule/LiquidityTooltip/index.tsx, yarn.lock
=> Jaycho 46/issue592

src/stories/molecule/LiquidityTooltip/index.tsx
- Show CLB token value and liquidity on each liquidity tooltips
=> fix: show clb token values and liquidity

src/index.css, src/pages/poolV3/index.tsx, src/stories/template/TradeManagementV3/style.css
- hide page bottom scroll-bar padding
- delete pool page bottom gradient 
- set TradeManagement text-align: left
=> fix: ui detail

src/App.tsx, src/hooks/usePythPrice.ts, src/hooks/useSubscribePythFeed.ts, src/lib/pyth/datafeed.ts, src/lib/pyth/streaming.ts, src/lib/pyth/subscribe.ts, src/stories/molecule/MarketSelectV3/hooks.tsx, src/stories/molecule/MarketSelectV3/index.tsx, src/typings/api.ts
=> Jaycho 46/issue594

src/index.css, src/pages/airdrop/index.tsx, src/stories/template/AirdropActivity/index.tsx, src/stories/template/AirdropZealyConnectModal/index.tsx, src/stories/template/AirdropZealyConnectModal/stories.ts, src/stories/template/AirdropZealyConvertModal/index.tsx, src/stories/template/AirdropZealyConvertModal/stories.ts, src/stories/template/Modal/style.css
- create [AirdropZealyConnectModal](https://github.com/chromatic-protocol/frontend/pull/599/commits/c4769a9a5937481b3237da5a825e4d9dfef5ddc5), [AirdropZealyConvertModal](https://github.com/chromatic-protocol/frontend/pull/599/commits/7a769d7b698be3429bd176e94dd6a6334d3f07c8)
*the new components can be visible in storybook
- add loading icon in zealy button
- update wording
=> Dia/airdrop update (zealy)

src/index.css, src/pages/airdrop/index.tsx, src/pages/poolV3/index.tsx, src/pages/tradeV3/index.tsx, src/stories/template/AirdropActivity/index.tsx, src/stories/template/AirdropStamp/index.tsx, src/stories/template/PoolMenu/index.tsx, src/stories/template/PoolMenuV3/index.tsx
- set min/max width of each pages, styles for screen-lg
- trade: 1360px ~
- pool: 1200px ~ 1480px
- airdrop: 1200px ~ 1400px
- faucet: 1200px ~
- update wording
=> Dia/page size,wording

codegen/performance.ts, src/constants/airdrop.ts, src/hooks/airdrops/useAirdropSync.ts, src/hooks/useCLPPerformace.ts, src/pages/airdrop/index.tsx, src/stories/template/AirdropActivity/index.tsx, src/stories/template/AirdropZealyConnectModal/index.tsx, src/stories/template/AirdropZealyConnectModal/stories.ts, src/stories/template/PoolPerformance/hooks.ts, src/stories/template/PoolPerformance/index.tsx, src/utils/link.ts, src/utils/number.ts
- Reset synced state with Zealy account when Airdrop modals are closed.
- Show profits and annual rates from each settlement tokens as CLP performances
=> fix: Airdrop Sync & CLP Performance

src/hooks/useTimeDifferences.ts, src/pages/airdrop/index.tsx, src/stories/atom/OptionInput/index.tsx, src/stories/molecule/PoolProgress/index.tsx, src/stories/molecule/PoolProgressV2/index.tsx, src/stories/molecule/PositionItem/hooks.tsx, src/stories/molecule/PositionItem/index.tsx, src/stories/molecule/PositionItemV2/hooks.tsx, src/stories/template/AirdropStamp/index.tsx, src/stories/template/PoolPanel/index.tsx, src/stories/template/PoolPanelV2/index.tsx, src/stories/template/TradeBar/index.tsx
- Show reset time with timezone
=> Airdrop hotfix

src/hooks/useTimeDifferences.ts, src/pages/airdrop/index.tsx, src/pages/poolV3/index.tsx, src/stories/template/AirdropStamp/index.tsx
- Show reset time with timezone
- Register CLPs on pool page
=> hotfix: reset time & register CLPs

src/stories/template/HeaderV3/index.tsx
- Show airdrop link on Header component
=> feat: show airdrop link

src/pages/airdrop/index.tsx
- Show notice modal on airdrop page
=> Hotfix: Modals on Airdrop page

src/pages/airdrop/index.tsx
- Remove notice modal on airdrop page
=> revert: notice modal on airdrop page

src/pages/airdrop/index.tsx
- Remove notice modal on airdrop page
=> Release from the develop branch

src/lib/pyth/subscribe.ts
=> Jaycho 46/issue607

src/pages/airdrop/index.tsx, src/stories/template/AirdropStamp/index.tsx
=> fix: use fixed utc string(+00:00)

codegen/analytics.ts, codegen/index.ts, package.json, src/hooks/useAnalytics.ts, src/lib/graphql/index.ts, src/pages/poolV3/index.tsx, src/stories/atom/Calendar/index.tsx, src/stories/atom/Calendar/stories.ts, src/stories/molecule/AnalyticsChart/index.tsx, src/stories/template/PoolAnalytics/index.tsx, src/stories/template/PoolAnalyticsV3/__mocks__/hooks.tsx, src/stories/template/PoolAnalyticsV3/hooks.tsx, src/stories/template/PoolAnalyticsV3/index.tsx, src/utils/date.ts, yarn.lock
=> Jaycho 46/issue521

src/stories/atom/Calendar/index.tsx, src/stories/atom/ChartLabel/index.tsx, src/stories/molecule/AnalyticsChart/index.tsx, src/stories/template/PoolAnalyticsV3/index.tsx, src/stories/template/PoolAnalyticsV3/style.css, src/stories/template/PoolPanelV2/index.tsx
PoolAnalytics
- loading, empty state ui
- chart label ui
- detail
=> Dia/pool chart UI detail

src/hooks/useTradeInput.ts, src/stories/molecule/AmountSwitch/index.tsx, src/stories/molecule/TradeContentV3/hooks.tsx, src/utils/log.ts, src/utils/trade.ts, src/utils/trading_fee.ts, yarn.lock
=> feat: find max allowable taker margin

src/stories/atom/Calendar/index.tsx, src/stories/molecule/WalletPopoverV3Body/index.tsx, src/stories/template/PoolPerformance/index.tsx
- import selectbox style
- update calendar button wording
- update "add metamask" button ui (in walletPopover)
=> Dia/fix UI

package.json, src/hooks/useFaucet.ts, src/pages/poolV3/index.tsx, src/stories/molecule/WalletPopoverV3Body/hooks.tsx, src/stories/molecule/WalletPopoverV3Body/index.tsx, src/utils/number.ts, yarn.lock
- Select LP by clicking liquidity items on Wallet popover
- Show pool analytics on pool page
- Show token amount on faucet page
=> Fix: Select LP on WalletPopoverV3 and Hotfix

src/stories/molecule/AccountPanelV3/hooks.tsx, src/stories/molecule/AccountPanelV3/index.tsx
in account panel, 
- add arrow icons in the buttons: deposit, withdraw
- add "wallet balance" info
*the ui will be updated later
=> hotfix-account

codegen/analytics.ts, src/hooks/useAnalytics.ts, src/stories/molecule/AnalyticsChart/index.tsx, src/stories/template/PoolAnalyticsV3/hooks.tsx, src/utils/date.ts
=> Jaycho 46/issue661

src/layouts/index.tsx, src/pages/trade/index.tsx, src/routes.tsx, src/stories/molecule/WalletPopoverV3Body/hooks.tsx, src/stories/template/Header/index.tsx, src/stories/template/HeaderV3/index.tsx, src/stories/template/TradeLiquidity/index.tsx
- Use updated route name for LP page
- `/pools` 
- Use redirect from `/pool` to `/pools`
- Render caution toasts after each pages are loaded
=> refactor: Update routes for pool page

src/apis/airdrop.ts, vite.config.ts
- Vite proxy config
- Handle requests to airdrop api in development
- Separated client urls to distinguish page routes and apis in development
- `/airdrop` - route of airdrop page
- `/api/airdrop` -> urls of airdrop api
=> refactor: Use proxy configs

.storybook/preview.tsx
- Prevent error messages when Storybook build
- `ExportNamedDeclaration`
=> fix: prevent error message
